version: 0.2

env:
  variables:
    S3_BUCKET: my-voting-appbucket
    LAMBDA_FUNCTION: VoteHandler
    REPOSITORY_URI: 851725585728.dkr.ecr.us-east-1.amazonaws.com/my-voting-app
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install awscli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 851725585728.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Deploying frontend to S3...
      - aws s3 sync frontend/ s3://$S3_BUCKET --delete
      - echo Deploying backend to Lambda...
      - zip function.zip lambda_function.py
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION --zip-file fileb://function.zip
      - echo Build and deployment finished on `date`

